name: Monitor Inventory

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Cache state files
      uses: actions/cache@v3
      with:
        path: |
          previous_stock_state.pickle
          previous_parts_state.pickle
          previous_chicken_discrepancy_state.pickle
          previous_gizzard_discrepancy_state.pickle
        key: inventory-state-v2-${{ github.run_number }}
        restore-keys: |
          inventory-state-v2-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create service account file
      run: |
        echo '${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}' > service-account.json
      env:
        ACTIONS_STEP_DEBUG: false
    
    - name: Run monitoring script
      env:
        SPACE_WEBHOOK_URL: ${{ secrets.SPACE_WEBHOOK_URL }}
        SPECIFICATION_SHEET_ID: ${{ secrets.SPECIFICATION_SHEET_ID }}
        INVENTORY_SHEET_ID: ${{ secrets.INVENTORY_SHEET_ID }}
        SERVICE_ACCOUNT_FILE: service-account.json
        ACTIONS_STEP_DEBUG: false
      run: |
        python monitor_combined.py