name: Monitor Inventory

on:
  schedule:
    - cron: '*/20 * * * *'  # Runs every 20 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Cache state files
      uses: actions/cache@v3
      with:
        path: |
          previous_stock_state.pickle
          previous_parts_state.pickle
          previous_chicken_discrepancy_state.pickle
          previous_gizzard_discrepancy_state.pickle
          failed_webhooks.json
        key: inventory-state-v2-${{ github.run_number }}
        restore-keys: |
          inventory-state-v2-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create service account file
      run: |
        echo '${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}' > service-account.json
      env:
        ACTIONS_STEP_DEBUG: false
    
    - name: Run data transformation
      id: transformation
      env:
        INVENTORY_SHEET_ID: ${{ secrets.INVENTORY_SHEET_ID }}
        INVENTORY_ETL_SPREADSHEET_ID: ${{ secrets.INVENTORY_ETL_SPREADSHEET_ID }}
        ACTIONS_STEP_DEBUG: false
      run: |
        if python transformation.py; then
          echo "TRANSFORMATION_SUCCESS=true" >> $GITHUB_ENV
        else
          echo "TRANSFORMATION_SUCCESS=false" >> $GITHUB_ENV
          exit 1
        fi

    - name: Wait for data propagation
      if: env.TRANSFORMATION_SUCCESS == 'true'
      run: sleep 30

    - name: Run monitoring script
      if: env.TRANSFORMATION_SUCCESS == 'true'
      env:
        SPACE_WEBHOOK_URL: ${{ secrets.SPACE_WEBHOOK_URL }}
        SPECIFICATION_SHEET_ID: ${{ secrets.SPECIFICATION_SHEET_ID }}
        INVENTORY_ETL_SPREADSHEET_ID: ${{ secrets.INVENTORY_ETL_SPREADSHEET_ID }}
        SERVICE_ACCOUNT_FILE: service-account.json
        ACTIONS_STEP_DEBUG: false
      run: |
        python monitor_combined.py

    - name: Check for failed webhooks and send email alert
      if: always()
      run: |
        if [ -f "failed_webhooks.json" ] && [ -s "failed_webhooks.json" ]; then
          echo "Failed webhooks detected. Preparing email alert..."
          FAILED_COUNT=$(wc -l < failed_webhooks.json)
          echo "FAILED_WEBHOOK_COUNT=$FAILED_COUNT" >> $GITHUB_ENV
          echo "FAILED_WEBHOOK_ALERT=true" >> $GITHUB_ENV
          echo "📧 Email alert will be sent for $FAILED_COUNT failed webhook(s)"

          # Create detailed email body with failed webhook details
          echo "Failed webhook notifications detected in Nasarawa inventory monitoring system." > email_body.txt
          echo "" >> email_body.txt
          echo "Number of failed webhooks: $FAILED_COUNT" >> email_body.txt
          echo "Run ID: ${{ github.run_number }}" >> email_body.txt
          echo "Time: $(date -u)" >> email_body.txt
          echo "" >> email_body.txt
          echo "Failed webhook details:" >> email_body.txt
          echo "========================" >> email_body.txt
          cat failed_webhooks.json >> email_body.txt
          echo "" >> email_body.txt
          echo "Please check the failed webhooks artifact for details:" >> email_body.txt
          echo "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> email_body.txt
          echo "" >> email_body.txt
          echo "This means inventory change notifications may not have been delivered to your Google Space." >> email_body.txt
        else
          echo "No failed webhooks found"
          echo "FAILED_WEBHOOK_ALERT=false" >> $GITHUB_ENV
        fi

    - name: Send email alert for failed webhooks
      if: always() && env.FAILED_WEBHOOK_ALERT == 'true'
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "🚨 Nasarawa Inventory: Failed Webhook Alert (${{ env.FAILED_WEBHOOK_COUNT }} failures)"
        to: ${{ secrets.EMAIL_RECIPIENTS }}
        from: ${{ secrets.EMAIL_SENDER }}
        body: file://email_body.txt

    - name: Upload failed webhooks as artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: failed-webhooks-${{ github.run_number }}
        path: failed_webhooks.json
        if-no-files-found: ignore
        retention-days: 30